AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: aws-student-upload
Resources:
    uploadStudentData:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
            CodeUri: .
            Description: aws-student-upload
            MemorySize: 512
            Timeout: 10
            Policies:
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - 'dynamodb:BatchWriteItem'
                            - 'dynamodb:GetItem'
                        Resource:
                            'Fn::Join':
                                - ''
                                - - 'arn:aws:dynamodb:'
                                  - Ref: 'AWS::Region'
                                  - ':'
                                  - Ref: 'AWS::AccountId'
                                  - ':table/studentsDB'
            Events:
                Api1:
                    Type: Api
                    Properties:
                        Path: /import
                        Method: POST
    studentsDB:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: studentsDB
            AttributeDefinitions:
                - AttributeName: email
                  AttributeType: S
            KeySchema:
                - AttributeName: email
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 2
                WriteCapacityUnits: 2
